FROM amazoncorretto:11
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENV SPRING_PROFILES_ACTIVE vault
ENV VAULT_TOKEN myroot
ENV VAULT_HOST 127.0.0.1
ENV VAULT_PORT 8200
ENV SERVER_PORT 8080
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app.jar"]