#This property file will be taken into consideration when building application. This will help to ensure build is success
server:
  port: 8888
spring:
  application:
    name: vault-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/spring-cloud-samples/config-repo # Public git repo to pass build
